ALTER TABLE "RoleplayState" ADD COLUMN "volatility" INTEGER NOT NULL DEFAULT 15;
ALTER TABLE "RoleplayState" ADD COLUMN "desire" INTEGER NOT NULL DEFAULT 20;
ALTER TABLE "RoleplayState" ADD COLUMN "inhibition" INTEGER NOT NULL DEFAULT 55;
ALTER TABLE "RoleplayState" ADD COLUMN "comfort" INTEGER NOT NULL DEFAULT 55;
